### ISSUE TITLE
Kafka Error after update to 22.12.0 form 22.11.0

### ISSUE THREAD

**Issue by aamarques** [getsentry/self-hosted#1894]
### Self-Hosted Version

22.11.0

### CPU Architecture

x86_64

### Docker Version

20.10.2

### Docker Compose Version

1.28.0

### Steps to Reproduce

Have a health setup running in 22.11.0 in docker machine (not in k8s).
```
CONTAINER ID   IMAGE                                    COMMAND                  CREATED       STATUS                             PORTS                                   NAMES
c2c5df89e9d4   nginx:1.22.0-alpine                      "/docker-entrypoint.…"   5 weeks ago   Up 2 minutes                       0.0.0.0:9000->80/tcp, :::9000->80/tcp   sentry-self-hosted_nginx_1
e39f87f7deb3   getsentry/relay:22.11.0                  "/bin/bash /docker-e…"   5 weeks ago   Up 2 minutes                       3000/tcp                                sentry-self-hosted_relay_1
f16ba1f49a6f   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   5 weeks ago   Up 25 seconds                      9000/tcp                                sentry-self-hosted_post-process-forwarder-transactions_1
3de78a7cfe57   sentry-cleanup-self-hosted-local         "/entrypoint.sh '0 0…"   5 weeks ago   Up 2 minutes                       9000/tcp                                sentry-self-hosted_sentry-cleanup_1
175ba780d704   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   5 weeks ago   Up 26 seconds                      9000/tcp                                sentry-self-hosted_subscription-consumer-events_1
38e53489c9be   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   5 weeks ago   Up 26 seconds                      9000/tcp                                sentry-self-hosted_ingest-consumer_1
d04502dd903c   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   5 weeks ago   Up 27 seconds (health: starting)   9000/tcp                                sentry-self-hosted_web_1
f8fd19544616   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   5 weeks ago   Up 25 seconds                      9000/tcp                                sentry-self-hosted_worker_1
a47dc19b00c5   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   5 weeks ago   Up 25 seconds                      9000/tcp                                sentry-self-hosted_subscription-consumer-transactions_1
f64bb991e17d   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   5 weeks ago   Up 25 seconds                      9000/tcp                                sentry-self-hosted_post-process-forwarder-errors_1
51ba56351e31   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   5 weeks ago   Up 25 seconds                      9000/tcp                                sentry-self-hosted_cron_1
8656fa1e0b10   getsentry/snuba:22.11.0                  "./docker_entrypoint…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-outcomes-consumer_1
53a731fce74d   snuba-cleanup-self-hosted-local          "/entrypoint.sh '*/5…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-transactions-cleanup_1
881f571408fa   getsentry/snuba:22.11.0                  "./docker_entrypoint…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-replacer_1
6fb5fc8e2047   snuba-cleanup-self-hosted-local          "/entrypoint.sh '*/5…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-cleanup_1
bb70c0301d0b   getsentry/snuba:22.11.0                  "./docker_entrypoint…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-subscription-consumer-transactions_1
1a08d906cb8e   getsentry/snuba:22.11.0                  "./docker_entrypoint…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-api_1
7a167c07c7f2   getsentry/snuba:22.11.0                  "./docker_entrypoint…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-sessions-consumer_1
fa57aab1a0ed   getsentry/snuba:22.11.0                  "./docker_entrypoint…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-subscription-consumer-events_1
2937f0030455   getsentry/snuba:22.11.0                  "./docker_entrypoint…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-consumer_1
46ef3d4fe0e6   getsentry/snuba:22.11.0                  "./docker_entrypoint…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-transactions-consumer_1
bf527d53802b   clickhouse-self-hosted-local             "/entrypoint.sh"         5 weeks ago   Up 2 minutes (healthy)             8123/tcp, 9000/tcp, 9009/tcp            sentry-self-hosted_clickhouse_1
210f087d951e   symbolicator-cleanup-self-hosted-local   "/entrypoint.sh '55 …"   5 weeks ago   Up 2 minutes                       3021/tcp                                sentry-self-hosted_symbolicator-cleanup_1
6db23b9de471   maxmindinc/geoipupdate:v4.7.1            "/usr/bin/geoipupdat…"   5 weeks ago   Exited (1) 5 weeks ago                                                     sentry-self-hosted_geoipupdate_1
95f8bc5bf472   tianon/exim4                             "docker-entrypoint.s…"   5 weeks ago   Up 2 minutes                       25/tcp                                  sentry-self-hosted_smtp_1
64961ab4fd84   postgres:9.6                             "/opt/sentry/postgre…"   5 weeks ago   Up 2 minutes (healthy)             5432/tcp                                sentry-self-hosted_postgres_1
5df18467679d   memcached:1.6.9-alpine                   "docker-entrypoint.s…"   5 weeks ago   Up 2 minutes (healthy)             11211/tcp                               sentry-self-hosted_memcached_1
83519c093f3d   getsentry/symbolicator:0.5.1             "/bin/bash /docker-e…"   5 weeks ago   Up 2 minutes                       3021/tcp                                sentry-self-hosted_symbolicator_1
af4f4cf1b466   confluentinc/cp-kafka:5.5.0              "/etc/confluent/dock…"   5 weeks ago   Up 2 minutes (health: starting)    9092/tcp                                sentry-self-hosted_kafka_1
48c1821b1f49   confluentinc/cp-zookeeper:5.5.0          "/etc/confluent/dock…"   5 weeks ago   Up 2 minutes (healthy)             2181/tcp, 2888/tcp, 3888/tcp            sentry-self-hosted_zookeeper_1
d6b624554f9b   redis:6.2.4-alpine                       "docker-entrypoint.s…"   5 weeks ago   Up 2 minutes (healthy)             6379/tcp                                sentry-self-hosted_redis_1
```
run the update commands
```
git fetch
git checkout 22.12.0
export REPORT_SELF_HOSTED_ISSUES=0
SENTRY_IMAGE=getsentry/sentry:22.12.0 ./install.sh
docker-compose up -d
```

### Expected Result

A clean and health update to 22.12.0

### Actual Result

No errors were reported in the update process.
I tried to execute the troubleshooting commands but got `Error: Assignments can only be reset if the group 'snuba-consumers' is inactive, but the current state is Stable.`, So I started only `zookeeper` and `kafka`, run the commands in troubleshooting but the error still.

```
CONTAINER ID   IMAGE                                    COMMAND                  CREATED          STATUS                          PORTS                                   NAMES
d74959747729   nginx:1.22.0-alpine                      "/docker-entrypoint.…"   44 seconds ago   Up 43 seconds                   0.0.0.0:9000->80/tcp, :::9000->80/tcp   sentry-self-hosted_nginx_1
35ed76b152b1   getsentry/relay:22.12.0                  "/bin/bash /docker-e…"   45 seconds ago   Up 44 seconds                   3000/tcp                                sentry-self-hosted_relay_1
2c7e68f310ac   sentry-cleanup-self-hosted-local         "/entrypoint.sh '0 0…"   2 minutes ago    Up 2 minutes                    9000/tcp                                sentry-self-hosted_sentry-cleanup_1
b10151b70827   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   2 minutes ago    Up 2 minutes                    9000/tcp                                sentry-self-hosted_post-process-forwarder-transactions_1
d7fc1bc7b1bf   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   2 minutes ago    Up 2 minutes                    9000/tcp                                sentry-self-hosted_subscription-consumer-events_1
688ba244d7cd   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   2 minutes ago    Up 2 minutes                    9000/tcp                                sentry-self-hosted_worker_1
a40d57f0f853   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   2 minutes ago    Up 2 minutes                    9000/tcp                                sentry-self-hosted_ingest-consumer_1
93bc1fd97cf4   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   2 minutes ago    Up 2 minutes (healthy)          9000/tcp                                sentry-self-hosted_web_1
9473de391b02   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   2 minutes ago    Up 2 minutes                    9000/tcp                                sentry-self-hosted_cron_1
17d007a6b6d3   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   2 minutes ago    Up 2 minutes                    9000/tcp                                sentry-self-hosted_post-process-forwarder-errors_1
a939e27c1e80   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   2 minutes ago    Up 2 minutes                    9000/tcp                                sentry-self-hosted_subscription-consumer-transactions_1
0301a5e30dc3   getsentry/snuba:22.12.0                  "./docker_entrypoint…"   2 minutes ago    Restarting (1) 10 seconds ago                                           sentry-self-hosted_snuba-consumer_1
9504b6fee05d   getsentry/snuba:22.12.0                  "./docker_entrypoint…"   2 minutes ago    Up 2 minutes                    1218/tcp                                sentry-self-hosted_snuba-subscription-consumer-events_1
c0405d49f3fb   getsentry/snuba:22.12.0                  "./docker_entrypoint…"   2 minutes ago    Restarting (1) 1 second ago                                             sentry-self-hosted_snuba-outcomes-consumer_1
55468739a2da   getsentry/snuba:22.12.0                  "./docker_entrypoint…"   2 minutes ago    Up 2 minutes                    1218/tcp                                sentry-self-hosted_snuba-subscription-consumer-transactions_1
10c519c12a64   getsentry/snuba:22.12.0                  "./docker_entrypoint…"   2 minutes ago    Up 2 minutes                    1218/tcp                                sentry-self-hosted_snuba-api_1
72a013b1f688   snuba-cleanup-self-hosted-local          "/entrypoint.sh '*/5…"   2 minutes ago    Up 2 minutes                    1218/tcp                                sentry-self-hosted_snuba-cleanup_1
b11969c5a329   snuba-cleanup-self-hosted-local          "/entrypoint.sh '*/5…"   2 minutes ago    Up 2 minutes                    1218/tcp                                sentry-self-hosted_snuba-transactions-cleanup_1
87558fa2ba12   getsentry/snuba:22.12.0                  "./docker_entrypoint…"   2 minutes ago    Up 2 minutes                    1218/tcp                                sentry-self-hosted_snuba-replacer_1
c253b4cccea7   getsentry/snuba:22.12.0                  "./docker_entrypoint…"   2 minutes ago    Up 2 minutes                    1218/tcp                                sentry-self-hosted_snuba-sessions-consumer_1
963f8014e309   getsentry/snuba:22.12.0                  "./docker_entrypoint…"   2 minutes ago    Up 2 minutes                    1218/tcp                                sentry-self-hosted_snuba-transactions-consumer_1
ecd788831648   symbolicator-cleanup-self-hosted-local   "/entrypoint.sh '55 …"   3 minutes ago    Up 3 minutes                    3021/tcp                                sentry-self-hosted_symbolicator-cleanup_1
08a379354787   clickhouse-self-hosted-local             "/entrypoint.sh"         3 minutes ago    Up 3 minutes (healthy)          8123/tcp, 9000/tcp, 9009/tcp            sentry-self-hosted_clickhouse_1
dbbf51d51720   maxmindinc/geoipupdate:v4.7.1            "/usr/bin/geoipupdat…"   3 minutes ago    Exited (1) 3 minutes ago                                                sentry-self-hosted_geoipupdate_1
4b48708d7157   postgres:9.6                             "/opt/sentry/postgre…"   8 minutes ago    Up 3 minutes (healthy)          5432/tcp                                sentry-self-hosted_postgres_1
1251d6717d78   memcached:1.6.9-alpine                   "docker-entrypoint.s…"   8 minutes ago    Up 3 minutes (healthy)          11211/tcp                               sentry-self-hosted_memcached_1
4c57e9e1edd8   tianon/exim4                             "docker-entrypoint.s…"   8 minutes ago    Up 3 minutes                    25/tcp                                  sentry-self-hosted_smtp_1
391f88d2cbc8   getsentry/symbolicator:0.6.0             "/bin/bash /docker-e…"   8 minutes ago    Up 3 minutes                    3021/tcp                                sentry-self-hosted_symbolicator_1
dea9567c6331   confluentinc/cp-kafka:5.5.0              "/etc/confluent/dock…"   8 minutes ago    Up 2 minutes (healthy)          9092/tcp                                sentry-self-hosted_kafka_1
9bd0856ac9ff   confluentinc/cp-zookeeper:5.5.0          "/etc/confluent/dock…"   9 minutes ago    Up 3 minutes (healthy)          2181/tcp, 2888/tcp, 3888/tcp            sentry-self-hosted_zookeeper_1
1ea7b69e2a97   redis:6.2.4-alpine                       "docker-entrypoint.s…"   9 minutes ago    Up 3 minutes (healthy)          6379/tcp                                sentry-self-hosted_redis_1
```

ERRORS in `sentry-self-hosted_snuba-consumer_1`
```
2022-12-29 09:57:27,217 Initializing Snuba...
2022-12-29 09:57:29,202 Snuba initialization took 1.9857687090000127s
2022-12-29 09:57:29,805 Initializing Snuba...
2022-12-29 09:57:31,876 Snuba initialization took 2.072255584000004s
2022-12-29 09:57:31,885 Consumer Starting
2022-12-29 09:57:31,886 librdkafka log level: 6
2022-12-29 09:57:34,153 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 574624709}
2022-12-29 09:57:34,154 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 187, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 218, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/src/snuba/snuba/utils/streams/kafka_consumer_with_commit_log.py", line 33, in poll
    return super().poll(timeout)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 450, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}
2022-12-29 09:57:34,156 Closing <snuba.utils.streams.kafka_consumer_with_commit_log.KafkaConsumerWithCommitLog object at 0x7efc7bd52730>...
2022-12-29 09:57:34,156 Partitions revoked: [Partition(topic=Topic(name='events'), index=0)]
2022-12-29 09:57:34,158 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 202, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 187, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 218, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/src/snuba/snuba/utils/streams/kafka_consumer_with_commit_log.py", line 33, in poll
    return super().poll(timeout)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 450, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}
```

ERRORS in `sentry-self-hosted_snuba-outcomes-consumer_1`

```
2022-12-29 10:00:18,064 Initializing Snuba...
2022-12-29 10:00:20,348 Snuba initialization took 2.284905971999933s
2022-12-29 10:00:20,978 Initializing Snuba...
2022-12-29 10:00:23,262 Snuba initialization took 2.2859040410000944s
2022-12-29 10:00:23,278 Consumer Starting
2022-12-29 10:00:23,278 librdkafka log level: 6
2022-12-29 10:00:25,311 New partitions assigned: {Partition(topic=Topic(name='outcomes'), index=0): 694350923}
2022-12-29 10:00:25,312 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 187, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 218, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 450, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}
2022-12-29 10:00:25,314 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f63b36544c0>...
2022-12-29 10:00:25,314 Partitions revoked: [Partition(topic=Topic(name='outcomes'), index=0)]
2022-12-29 10:00:25,316 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 202, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 187, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 218, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 450, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}

```

**Comment by aamarques** [comment]
This issue was _**closed/copied**_ from https://github.com/getsentry/sentry/issues/42693 to here (self-hosted)

**Comment by aamarques** [comment]
I have tried the [[suggestions in the troubleshooting section of the docs](https://develop.sentry.dev/self-hosted/troubleshooting/#kafka) but not the nuclear option - It's not an option for me.
It didn't work as I wrote it in the Actual Result session above.

This seems to be related to AUTO_OFFSET_RESET and not to OFFSET OUT OF RANGE in Kafka but I have no expertise.

**Comment by hubertdeng123** [comment]
Hmmmm, wondering if this may have to do with this [fix](https://github.com/getsentry/self-hosted/pull/1817).

**Comment by hubertdeng123** [comment]
Did you completely shut down your consumer groups? Looking at this:
https://stackoverflow.com/questions/48866690/how-to-shift-back-the-offset-of-a-topic-within-a-stable-kafka-consumer-group

**Comment by aamarques** [comment]
> Hmmmm, wondering if this may have to do with this [fix](https://github.com/getsentry/self-hosted/pull/1817).

@hubertdeng123 I think also.
I changed back the values to  22.11.0 docker-compose.yml and these services are ok BUT I have a problem now in 
`sentry-self-hosted_snuba-transactions-consumer_1`

old values:
```
 interval: 3s
 timeout: 600s
 retries: 200
```

Log of error
```
2023-01-04 11:37:39,454 Closing <snuba.utils.streams.kafka_consumer_with_commit_log.KafkaConsumerWithCommitLog object at 0x7fe48a0836d0>...
2023-01-04 11:37:39,454 Partitions revoked: [Partition(topic=Topic(name='transactions'), index=0)]
2023-01-04 11:37:39,456 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 202, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 187, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 218, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/src/snuba/snuba/utils/streams/kafka_consumer_with_commit_log.py", line 33, in poll
    return super().poll(timeout)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 450, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}
```

**Comment by aamarques** [comment]
> Did you completely shut down your consumer groups? Looking at this: https://stackoverflow.com/questions/48866690/how-to-shift-back-the-offset-of-a-topic-within-a-stable-kafka-consumer-group

Let me do it and post asap

**Comment by aamarques** [comment]
@hubertdeng123 
**Now the scenario is:**

- update from 22.11.0 to 22.12.0
- docker-compose.yml (22.12.0) replacing with 22.1.0 values
```
     interval: 3s
     timeout: 600s
     retries: 200
       
     command: consumer --storage transactions --consumer-group transactions_group --auto-offset-reset=latest --max-batch-time-ms 750 --commit-log-topic=snuba-commit-log
```

**Result:**

- The same error, now  at `sentry-self-hosted_snuba-outcomes-consumer_1`  

**Resolution:**
- delete offsets from topic outcomes and restart sentry

`docker-compose run --rm kafka kafka-consumer-groups --bootstrap-server kafka:9092 --group snuba-consumers --topic outcomes --delete-offset`

**Question:**

- What is the consequence of delete-offsets?
- This will cause information lost? 


PS: I tried to reset offsets but they are actives

Cheers

**Comment by hubertdeng123** [comment]
Yeah, the `delete-offsets` has the potential for data loss. This is useful information though, thanks for bringing this up.

**Comment by hubertdeng123** [comment]
For now, is your Sentry setup healthy again?

**Comment by aamarques** [comment]
> Yeah, the `delete-offsets` has the potential for data loss. This is useful information though, thanks for bringing this up.

So, is there another approach?

**Comment by aamarques** [comment]
> For now, is your Sentry setup healthy again?

Yes, after `delete-offsets`

**Comment by hubertdeng123** [comment]
There is unfortunately not another approach as of now.

**Comment by aldy505** [comment]
This is what I did after getting around 28K entries of KafkaError.

```bash
sudo docker compose down && \
sudo docker compose up -d kafka && \
sleep 60s && \ # Make sure our Kafka is ready to handle commands
sudo docker compose run --rm kafka kafka-consumer-groups --bootstrap-server kafka:9092 --group snuba-post-processor --delete && \
sudo docker compose run --rm kafka kafka-consumer-groups --bootstrap-server kafka:9092 --group snuba-consumers --topic snuba-commit-log --delete-offsets && \
sudo docker compose run --rm kafka kafka-consumer-groups --bootstrap-server kafka:9092 --group snuba-consumers --topic snuba-commit-log --delete-offsets && \
sudo docker compose run --rm kafka kafka-consumer-groups --bootstrap-server kafka:9092 --group snuba-consumers --delete && \
sleep 60s && \ # Make sure everything is commited on Kafka's side
sudo docker compose up -d # To start everything again
```

If anyone still encounter any issues, they should change the `docker-compose.yml` file to:

```yaml
  snuba-transactions-consumer:
    <<: *snuba_defaults
    command: consumer --storage transactions --consumer-group transactions_group --auto-offset-reset=latest --max-batch-time-ms 750 --commit-log-topic=snuba-commit-log # This line
  snuba-replacer:
    <<: *snuba_defaults
    command: replacer --storage errors --auto-offset-reset=latest --max-batch-size 3 # And this line
```

And then do `sudo docker compose up -d` again. You'll probably still get the same error. When you do, execute the commands on the bash block above, then replace the value of `docker-compose.yml` back to:

```yaml
  snuba-transactions-consumer:
    <<: *snuba_defaults
    command: consumer --storage transactions --consumer-group transactions_group --auto-offset-reset=latest --max-batch-time-ms 750
  snuba-replacer:
    <<: *snuba_defaults
    command: replacer --storage errors --auto-offset-reset=latest
```

Hope this is helpful to others.

**Comment by LorenDorez** [comment]
Thanks @aldy505, your solution help me fix the same issue. Nothing else seems to work.

**Comment by smarakdas314** [comment]
Same here @aldy505 solution helped me, official solution didn't work, so deleting offsets helped

```
root@sentry /srv/sentry # docker compose run --rm kafka kafka-consumer-groups --bootstrap-server kafka:9092 --group snuba-consumers --topic events --reset-offsets --to-latest
[+] Running 1/0
 ⠿ Container sentry-self-hosted-zookeeper-1  Running                                                                                                                                                                                                                       0.0s

Error: Assignments can only be reset if the group 'snuba-consumers' is inactive, but the current state is Stable.
```

**Comment by aamarques** [comment]
And this happened again with `ingest-sessions` topic.
What work for me is just `delete-offsets` for the topic showing an error. 
You do not need to `delete-offsets `for all topics

```
$ docker-compose run --rm kafka kafka-consumer-groups --bootstrap-server kafka:9092 --group snuba-consumers --topic ingest-sessions --delete-offsets
Request succeed for deleting offsets with topic ingest-sessions group snuba-consumers
Creating sentry-self-hosted_kafka_run ... done

TOPIC                          PARTITION       STATUS
ingest-sessions                0               Successful

```

Cheers.

**Comment by LorenDorez** [comment]
Same here it keeps happening and we keep having to run the above commands. @hubertdeng123 any idea why this keeps happening?

**Comment by hubertdeng123** [comment]
This will need more investigation, putting on the backlog for now

**Comment by sklibanov312** [comment]
@aldy505 thanks - I was experiencing the same situation with on-prem 23.1.1 installed by the book according to https://develop.sentry.dev/self-hosted/ . Followed those steps, problem stopped. Thanks again.

**Comment by LorenDorez** [comment]
@aldy505 @smarakdas314  @aamarques @sklibanov312 

Can i ask what version of sentry all of you are running? im on 23.1.1

**Comment by aldy505** [comment]
> Can i ask what version of sentry all of you are running? im on 23.1.1
> 
> 

@LorenDorez I was upgrading from 22.12.0 to 23.1.0. The problem occurred to me since 23.1.0. I fixed it (by running those commands) on 23.1.1. The error never showed up again from that moment.

**Comment by moritzhabegger** [comment]
This problem really makes Sentry unusable for us, since we heavily depend on the push notifications on Slack. We tried the proposed commands but this offset problem keeps coming back after a couple of days. We are running version 23.1.1

**Comment by LorenDorez** [comment]
This just happened again to me this morning on a new install box i setup. There isnt even anything using that box yet so its not a load/usage issue.

**Comment by bobvandevijver** [comment]
This is still happening with 23.4.0.

**Comment by Natgho** [comment]
Still happening...

**Comment by jstdoit** [comment]
Still happening...

**Comment by LorenDorez** [comment]
Same here as well. At this point i just run a script everytime to reset this. However, this is becoming tedious so might have to look at other options at this point since we havent heard from any one @ sentry but definitely seems to be an issue in the Self-Hosted setup

**Comment by zerkms** [comment]
I have found that it starts happening to us as long as we simply restart the sentry instance (using `docker-compose up/down`).

**Comment by aldy505** [comment]
This happened again on my own instance after a long time of not having it (since around February 2023). I'm on 23.4.0 now, and it's been 1 month since the upgrade. But from the breadcrumb's of @LorenDorez (here https://github.com/getsentry/self-hosted/issues/1894#issuecomment-1489093317), mine was stating that it comes from the topic "transaction", meaning that the problem's not on a specific topic whatsoever. 

One thing in common is that the Kafka topics was being consumed by [arroyo](https://github.com/getsentry/arroyo) (Sentry's Kafka library to consume, publish, handle [DLQ](https://en.wikipedia.org/wiki/Dead_letter_queue), and more -- see [their docs](https://getsentry.github.io/arroyo/index.html)). I don't know whether my assumptions are correct, but I think this is about either error handling on the arroyo library itself for handling offset out of range, or error handling on the [sentry](https://github.com/getsentry/sentry) repo.

But unlike [zerkms on their previous comment](https://github.com/getsentry/self-hosted/issues/1894#issuecomment-1540974820), I don't do `docker compose up/down`. The machine was left untouched by human, and was not restarted.

![image](https://github.com/getsentry/self-hosted/assets/7274326/1aac3710-9ca8-40be-a0a5-cd99ab68d135)

**Comment by zerkms** [comment]
@aldy505 it happens on `transaction` topic to me as well (and only to it).

**Comment by hubertdeng123** [comment]
Merged a [PR](https://github.com/getsentry/self-hosted/pull/2144) that went in with the 23.5.0 release. It adds the `--no-strict-offset-reset` option to all snuba consumers. Hopefully this will solve the issue for you all 🤞

**Comment by zerkms** [comment]
@aldy505 I use that very comment yep - I drop a few topics and restart. But hopefully after :point_up: nothing of that is needed anymore :-)

**Comment by LorenDorez** [comment]
@hubertdeng123 do you know if we need to upgrade to 23.5.0 first or can we try setting those flags in the existing version?

**Comment by bobvandevijver** [comment]
I'm still seeing this after the upgrade to 23.5.0, but it could be that it was already happening before the update. Will run the fix script one more time, and hope it is solved definitively afterwards...

**Comment by ZhaoKai-Kaiser** [comment]
Is there any new progress?

**Comment by sertxudev** [comment]
@Kai-93 Since the last upgrade I have no longer seen this error. If you already upgraded try running the fix script as @bobvandevijver suggested.

**Comment by hubertdeng123** [comment]
Glad to hear this @sertxudev. @bobvandevijver is this still happening for you?

**Comment by Kai-93** [comment]
```
   post-process-forwarder-errors:
     <<: *sentry_defaults
-    command: run post-process-forwarder --entity errors
+    command: run post-process-forwarder --entity errors --no-strict-offset-reset
 
   post-process-forwarder-transactions:
     <<: *sentry_defaults
-    command: run post-process-forwarder --entity transactions --commit-log-topic=snuba-transactions-commit-log --synchronize-commit-group transactions_group
+    command: run post-process-forwarder --entity transactions --commit-log-topic=snuba-transactions-commit-log --synchronize-commit-group transactions_group  --no-strict-offset-reset
   subscription-consumer-events:
     <<: *sentry_defaults
     command: run query-subscription-consumer --topic events-subscription-results
```

I added this to make post-process-forwarder-transactions and post-process-forwarder-errors no longer restart, but the following errors are still happening

post-process-forwarder-errors:
```
2023-05-31T00:48:35.678488770Z %4|1685494115.678|OFFSET|rdkafka#consumer-1| [thrd:main]: events [0]: offset reset (at offset 12325, broker 1001) to END: fetch failed due to requested offset not available on the broker: Broker: Offset out of range
```

post-process-forwarder-transactions：
```
2023-05-22T00:46:37.408887095Z %4|1684716397.408|OFFSET|rdkafka#consumer-1| [thrd:main]: transactions [0]: offset reset (at offset 24, broker 1001) to END: fetch failed due to requested offset not available on the broker: Broker: Offset out of range
```

**Comment by LiXiangYu** [comment]
Dear engineers, is this problem solved now? I still find this issue in version 23.5.0

**Comment by LiXiangYu** [comment]
> @Kai-93 Since the last upgrade I have no longer seen this error. If you already upgraded try running the fix script as @bobvandevijver suggested.

hi，brother。How did you do that？

**Comment by aldy505** [comment]
> Dear engineers, is this problem solved now? I still find this issue in version 23.5.0

@LiXiangYu Try running the cleanup command I posted above (a long way up), then upgrade to 25.6.1.

**Comment by bobvandevijver** [comment]
@hubertdeng123 I am still seeing it on one instance, but I believe I missed this one with the script (I have three instances, two haven't been logging the error for quite some time now).

However, which might be related to this, I am seeing some notifications being generator after a lot more time then it should. Think of hours late instead of almost instantaneously.

**Comment by hubertdeng123** [comment]
Great to hear :) 

I'm going to close this as I believe this is resolved.
