### ISSUE TITLE
Deleting a replay record leads to snuba-replays-consumer crash

### ISSUE THREAD

**Issue by alexphili** [getsentry/self-hosted#2042]
### Self-Hosted Version

23.3.1

### CPU Architecture

x86_64

### Docker Version

23.0.1

### Docker Compose Version

2.16.0

### Steps to Reproduce

Enable replay and go to a replay event in the ui and click delete

### Expected Result

Replay record should be deleted.

### Actual Result

After clicking on the delete button, the container "snuba-replays-consumer" keeps crashing

Here are the logs of the containers:

```
2023-03-24 14:39:34,939 Initializing Snuba...
2023-03-24 14:39:38,254 Snuba initialization took 3.316148126963526s
2023-03-24 14:39:39,007 Initializing Snuba...
2023-03-24 14:39:42,611 Snuba initialization took 3.606418968993239s
2023-03-24 14:39:42,620 Consumer Starting
2023-03-24 14:39:42,620 librdkafka log level: 6
2023-03-24 14:39:44,333 New partitions assigned: {Partition(topic=Topic(name='ingest-replay-events'), index=0): 22}
2023-03-24 14:39:46,341 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 181, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 221, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/dead_letter_queue/dead_letter_queue.py", line 39, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task.py", line 71, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/reduce.py", line 149, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task.py", line 151, in poll
    result = future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/snuba/snuba/consumers/strategy_factory.py", line 120, in flush_batch
    message.payload.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 296, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 135, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 328, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 266, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Cannot parse JSON string: expected opening quote: (while read the value of key platform): (at row 1)```


### Event ID

87057f1c1a5046ecb6bd7516f38c5aa8

**Comment by hubertdeng123** [comment]
@JoshFerge Maybe we need to set empty string instead of null for items with items with key `platform` too?

**Comment by JoshFerge** [comment]
I think https://github.com/getsentry/snuba/pull/3908 should fix -- will try and write a test case today. thanks for reporting.

**Comment by JoshFerge** [comment]
This should be fixed in next self hosted release by https://github.com/getsentry/sentry/pull/46396, if not, please let us know!

**Comment by tm1000** [comment]
Is there a way to help this situation if someone already clicked delete. I tried to restart the containers but it just starts crashing again.

**Comment by alexphili** [comment]
@tm1000 You have to delete the topic which is crashing, stop all containers then ./install.sh to rebuild the topic.

**Comment by tm1000** [comment]
This is still broken in #2055 even after using the commit that should have fixed it (well now its a different key)
