### ISSUE TITLE
Replays not appearing in sentry even though 200 response

### ISSUE THREAD

**Issue by ffaen** [getsentry/self-hosted#2057]
### Self-Hosted Version

23.3.1 (also 23.4.0, 23.5.0)

### CPU Architecture

x86_64

### Docker Version

20.10.12

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. Upgrade from 23.3.0 (previously 22.9.0)
2. Attempt to start a replay session (using the Vue js sdk)
3. Events sent through the application get a 200 message, but don't appear to be processing correctly on the backend

### Expected Result

Upon starting a replay session I expect to see a replay event start on sentry.

### Actual Result

<details><summary>Last install script:</summary>

```
▶ Parsing command line ...

▶ Detecting Docker platform
Detected Docker platform is linux/amd64

▶ Initializing Docker Compose ...

▶ Setting up error handling ...
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM debian:bullseye-slim
 ---> 224855429754
Step 2/4 : LABEL MAINTAINER="oss@sentry.io"
 ---> Using cache
 ---> bfa28f611743
Step 3/4 : RUN set -x   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq   && apt-get clean   && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 4dcba2c7f9da
Step 4/4 : ENTRYPOINT ["jq"]
 ---> Using cache
 ---> 8a9500170a2b
Successfully built 8a9500170a2b
Successfully tagged sentry-self-hosted-jq-local:latest

Hey, so ... we would love to automatically find out about issues with your
Sentry instance so that we can improve the product. Turns out there is an app
for that, called Sentry. Would you be willing to let us automatically send data
about your instance upstream to Sentry for development and debugging purposes?

  y / yes / 1
  n / no / 0

(Btw, we send this to our own self-hosted Sentry instance, not to Sentry SaaS,
so that we can be in this together.)

Here's the info we may collect:

  - OS username
  - IP address
  - install log
  - runtime errors
  - performance data

Thirty (30) day retention. No marketing. Privacy policy at sentry.io/privacy.

y or n?
Thank you. To avoid this prompt in the future, use one of these flags:

  --report-self-hosted-issues
  --no-report-self-hosted-issues

or set the REPORT_SELF_HOSTED_ISSUES environment variable:

  REPORT_SELF_HOSTED_ISSUES=1 to send data
  REPORT_SELF_HOSTED_ISSUES=0 to not send data

latest: Pulling from getsentry/sentry-cli
d261077062b2: Already exists
9ec3a6ac5a4a: Already exists
a02410363526: Already exists
6c84fca2b280: Already exists
ec5f74ed37e1: Pulling fs layer
ec5f74ed37e1: Verifying Checksum
ec5f74ed37e1: Download complete
ec5f74ed37e1: Pull complete
Digest: sha256:714d866fd1a28512879d2d0dde87d7f0d96758170973ed60b346b1b9563efcd3
Status: Downloaded newer image for getsentry/sentry-cli:latest
docker.io/getsentry/sentry-cli:latest

▶ Checking for latest commit ...
skipped

▶ Checking minimum requirements ...
Found Docker version 20.10.12
Found Docker Compose version 1.29.2

▶ Turning things off ...
Stopping sentry-self-hosted_nginx_1                                    ...
Stopping sentry-self-hosted_relay_1                                    ...
Stopping sentry-self-hosted_cron_1                                     ...
Stopping sentry-self-hosted_web_1                                      ...
Stopping sentry-self-hosted_subscription-consumer-events_1             ...
Stopping sentry-self-hosted_sentry-cleanup_1                           ...
Stopping sentry-self-hosted_subscription-consumer-transactions_1       ...
Stopping sentry-self-hosted_post-process-forwarder-transactions_1      ...
Stopping sentry-self-hosted_ingest-consumer_1                          ...
Stopping sentry-self-hosted_worker_1                                   ...
Stopping sentry-self-hosted_post-process-forwarder-errors_1            ...
Stopping sentry-self-hosted_ingest-replay-recordings_1                 ...
Stopping sentry-self-hosted_snuba-subscription-consumer-transactions_1 ...
Stopping sentry-self-hosted_snuba-transactions-consumer_1              ...
Stopping sentry-self-hosted_snuba-subscription-consumer-events_1       ...
Stopping sentry-self-hosted_snuba-consumer_1                           ...
Stopping sentry-self-hosted_snuba-outcomes-consumer_1                  ...
Stopping sentry-self-hosted_snuba-api_1                                ...
Stopping sentry-self-hosted_snuba-sessions-consumer_1                  ...
Stopping sentry-self-hosted_snuba-subscription-consumer-sessions_1     ...
Stopping sentry-self-hosted_snuba-replacer_1                           ...
Stopping sentry-self-hosted_snuba-replays-consumer_1                   ...
Stopping sentry-self-hosted_clickhouse_1                               ...
Stopping sentry-self-hosted_symbolicator-cleanup_1                     ...
Stopping sentry-self-hosted_smtp_1                                     ...
Stopping sentry-self-hosted_memcached_1                                ...
Stopping sentry-self-hosted_postgres_1                                 ...
Stopping sentry-self-hosted_symbolicator_1                             ...
Stopping sentry-self-hosted_kafka_1                                    ...
Stopping sentry-self-hosted_zookeeper_1                                ...
Stopping sentry-self-hosted_redis_1                                    ...
Stopping sentry-self-hosted_nginx_1                                    ... done
Stopping sentry-self-hosted_post-process-forwarder-transactions_1      ... done
Stopping sentry-self-hosted_worker_1                                   ... done
Stopping sentry-self-hosted_snuba-replays-consumer_1                   ... done
Stopping sentry-self-hosted_snuba-subscription-consumer-sessions_1     ... done
Stopping sentry-self-hosted_relay_1                                    ... done
Stopping sentry-self-hosted_web_1                                      ... done
Stopping sentry-self-hosted_subscription-consumer-events_1             ... done
Stopping sentry-self-hosted_ingest-consumer_1                          ... done
Stopping sentry-self-hosted_ingest-replay-recordings_1                 ... done
Stopping sentry-self-hosted_post-process-forwarder-errors_1            ... done
Stopping sentry-self-hosted_subscription-consumer-transactions_1       ... done
Stopping sentry-self-hosted_cron_1                                     ... done
Stopping sentry-self-hosted_symbolicator-cleanup_1                     ... done
Stopping sentry-self-hosted_sentry-cleanup_1                           ... done
Stopping sentry-self-hosted_smtp_1                                     ... done
Stopping sentry-self-hosted_postgres_1                                 ... done
Stopping sentry-self-hosted_snuba-outcomes-consumer_1                  ... done
Stopping sentry-self-hosted_snuba-subscription-consumer-events_1       ... done
Stopping sentry-self-hosted_snuba-api_1                                ... done
Stopping sentry-self-hosted_snuba-transactions-consumer_1              ... done
Stopping sentry-self-hosted_memcached_1                                ... done
Stopping sentry-self-hosted_snuba-consumer_1                           ... done
Stopping sentry-self-hosted_snuba-sessions-consumer_1                  ... done
Stopping sentry-self-hosted_snuba-replacer_1                           ... done
Stopping sentry-self-hosted_snuba-subscription-consumer-transactions_1 ... done
Stopping sentry-self-hosted_redis_1                                    ... done
Stopping sentry-self-hosted_kafka_1                                    ... done
Stopping sentry-self-hosted_zookeeper_1                                ... done
Stopping sentry-self-hosted_clickhouse_1                               ... done
Stopping sentry-self-hosted_symbolicator_1                             ... done
Removing sentry-self-hosted_nginx_1                                    ...
Removing sentry-self-hosted_relay_1                                    ...
Removing sentry-self-hosted_cron_1                                     ...
Removing sentry-self-hosted_web_1                                      ...
Removing sentry-self-hosted_subscription-consumer-events_1             ...
Removing sentry-self-hosted_sentry-cleanup_1                           ...
Removing sentry-self-hosted_subscription-consumer-transactions_1       ...
Removing sentry-self-hosted_post-process-forwarder-transactions_1      ...
Removing sentry-self-hosted_ingest-consumer_1                          ...
Removing sentry-self-hosted_worker_1                                   ...
Removing sentry-self-hosted_post-process-forwarder-errors_1            ...
Removing sentry-self-hosted_ingest-replay-recordings_1                 ...
Removing sentry-self-hosted_snuba-subscription-consumer-transactions_1 ...
Removing sentry-self-hosted_snuba-transactions-consumer_1              ...
Removing sentry-self-hosted_snuba-subscription-consumer-events_1       ...
Removing sentry-self-hosted_snuba-consumer_1                           ...
Removing sentry-self-hosted_snuba-outcomes-consumer_1                  ...
Removing sentry-self-hosted_snuba-api_1                                ...
Removing sentry-self-hosted_snuba-sessions-consumer_1                  ...
Removing sentry-self-hosted_snuba-subscription-consumer-sessions_1     ...
Removing sentry-self-hosted_snuba-replacer_1                           ...
Removing sentry-self-hosted_snuba-replays-consumer_1                   ...
Removing sentry-self-hosted_clickhouse_1                               ...
Removing sentry-self-hosted_symbolicator-cleanup_1                     ...
Removing sentry-self-hosted_smtp_1                                     ...
Removing sentry-self-hosted_memcached_1                                ...
Removing sentry-self-hosted_postgres_1                                 ...
Removing sentry-self-hosted_symbolicator_1                             ...
Removing sentry-self-hosted_kafka_1                                    ...
Removing sentry-self-hosted_zookeeper_1                                ...
Removing sentry-self-hosted_redis_1                                    ...
Removing sentry-self-hosted_snuba-subscription-consumer-transactions_1 ... done
Removing sentry-self-hosted_post-process-forwarder-transactions_1      ... done
Removing sentry-self-hosted_redis_1                                    ... done
Removing sentry-self-hosted_smtp_1                                     ... done
Removing sentry-self-hosted_snuba-subscription-consumer-sessions_1     ... done
Removing sentry-self-hosted_snuba-api_1                                ... done
Removing sentry-self-hosted_memcached_1                                ... done
Removing sentry-self-hosted_subscription-consumer-events_1             ... done
Removing sentry-self-hosted_ingest-replay-recordings_1                 ... done
Removing sentry-self-hosted_nginx_1                                    ... done
Removing sentry-self-hosted_snuba-transactions-consumer_1              ... done
Removing sentry-self-hosted_snuba-outcomes-consumer_1                  ... done
Removing sentry-self-hosted_snuba-replacer_1                           ... done
Removing sentry-self-hosted_ingest-consumer_1                          ... done
Removing sentry-self-hosted_worker_1                                   ... done
Removing sentry-self-hosted_clickhouse_1                               ... done
Removing sentry-self-hosted_subscription-consumer-transactions_1       ... done
Removing sentry-self-hosted_symbolicator_1                             ... done
Removing sentry-self-hosted_cron_1                                     ... done
Removing sentry-self-hosted_zookeeper_1                                ... done
Removing sentry-self-hosted_sentry-cleanup_1                           ... done
Removing sentry-self-hosted_snuba-subscription-consumer-events_1       ... done
Removing sentry-self-hosted_web_1                                      ... done
Removing sentry-self-hosted_postgres_1                                 ... done
Removing sentry-self-hosted_snuba-consumer_1                           ... done
Removing sentry-self-hosted_post-process-forwarder-errors_1            ... done
Removing sentry-self-hosted_symbolicator-cleanup_1                     ... done
Removing sentry-self-hosted_relay_1                                    ... done
Removing sentry-self-hosted_snuba-replays-consumer_1                   ... done
Removing sentry-self-hosted_kafka_1                                    ... done
Removing sentry-self-hosted_snuba-sessions-consumer_1                  ... done
Removing network sentry-self-hosted_default

▶ Creating volumes for persistent storage ...
Created sentry-clickhouse.
Created sentry-data.
Created sentry-kafka.
Created sentry-postgres.
Created sentry-redis.
Created sentry-symbolicator.
Created sentry-zookeeper.

▶ Ensuring files from examples ...
sentry/sentry.conf.py already exists, skipped creation.
sentry/config.yml already exists, skipped creation.
symbolicator/config.yml already exists, skipped creation.

▶ Ensuring Relay credentials ...
relay/config.yml already exists, skipped creation.
relay/credentials.json already exists, skipped creation.

▶ Generating secret key ...

▶ Fetching and updating Docker images ...
Some service image(s) must be built from source by running:
    docker-compose build cron ingest-consumer web post-process-forwarder-transactions subscription-consumer-transactions post-process-forwarder-errors sentry-cleanup worker symbolicator-cleanup clickhouse subscription-consumer-events ingest-replay-recordings
23.3.1: Pulling from getsentry/sentry
7a6db449b51b: Already exists
e238bceb2957: Already exists
9c37eda4ff12: Already exists
120078faa760: Already exists
2d3523ccd6f4: Already exists
fc89a2b5b7c8: Pulling fs layer
61478a58a5c1: Pulling fs layer
e0eb6e182585: Pulling fs layer
854169529079: Pulling fs layer
79d8b43f58f6: Pulling fs layer
0dd26c28698b: Pulling fs layer
01851f8c53e4: Pulling fs layer
d5eae154021f: Pulling fs layer
b150162d5f13: Pulling fs layer
79d8b43f58f6: Waiting
0dd26c28698b: Waiting
66a7c2a6e096: Pulling fs layer
01851f8c53e4: Waiting
d5eae154021f: Waiting
b150162d5f13: Waiting
66a7c2a6e096: Waiting
854169529079: Waiting
fc89a2b5b7c8: Download complete
fc89a2b5b7c8: Pull complete
e0eb6e182585: Download complete
61478a58a5c1: Verifying Checksum
61478a58a5c1: Download complete
61478a58a5c1: Pull complete
e0eb6e182585: Pull complete
79d8b43f58f6: Verifying Checksum
79d8b43f58f6: Download complete
0dd26c28698b: Verifying Checksum
0dd26c28698b: Download complete
d5eae154021f: Verifying Checksum
d5eae154021f: Download complete
b150162d5f13: Verifying Checksum
b150162d5f13: Download complete
01851f8c53e4: Verifying Checksum
01851f8c53e4: Download complete
66a7c2a6e096: Verifying Checksum
66a7c2a6e096: Download complete
854169529079: Verifying Checksum
854169529079: Download complete
854169529079: Pull complete
79d8b43f58f6: Pull complete
0dd26c28698b: Pull complete
01851f8c53e4: Pull complete
d5eae154021f: Pull complete
b150162d5f13: Pull complete
66a7c2a6e096: Pull complete
Digest: sha256:f8f918c2f4293bdb75266c424f05808779b1e634f27b83d43b3142e6264048d1
Status: Downloaded newer image for getsentry/sentry:23.3.1
docker.io/getsentry/sentry:23.3.1

▶ Building and tagging Docker images ...

Building web
Sending build context to Docker daemon  32.26kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 71796743f12f
Step 3/5 : COPY . /usr/src/sentry
 ---> 3029cebf4212
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Running in ef65a6592dbf
Removing intermediate container ef65a6592dbf
 ---> fe02ba5be9a9
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Running in d2643fc9e5fe
sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Removing intermediate container d2643fc9e5fe
 ---> 15f5dafe46f4
Successfully built 15f5dafe46f4
Successfully tagged sentry-self-hosted-local:latest
smtp uses an image, skipping
memcached uses an image, skipping
redis uses an image, skipping
postgres uses an image, skipping
zookeeper uses an image, skipping
kafka uses an image, skipping
Building clickhouse
Sending build context to Docker daemon  3.584kB
Step 1/2 : ARG BASE_IMAGE
Step 2/2 : FROM ${BASE_IMAGE}
 ---> abe55fc6544d
Successfully built abe55fc6544d
Successfully tagged clickhouse-self-hosted-local:latest
geoipupdate uses an image, skipping
snuba-api uses an image, skipping
snuba-consumer uses an image, skipping
snuba-outcomes-consumer uses an image, skipping
snuba-sessions-consumer uses an image, skipping
snuba-transactions-consumer uses an image, skipping
snuba-replays-consumer uses an image, skipping
snuba-replacer uses an image, skipping
snuba-subscription-consumer-events uses an image, skipping
snuba-subscription-consumer-sessions uses an image, skipping
snuba-subscription-consumer-transactions uses an image, skipping
symbolicator uses an image, skipping
Building symbolicator-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/8 : ARG BASE_IMAGE
Step 2/8 : FROM ${BASE_IMAGE}
 ---> 3aef8fe5628c
Step 3/8 : USER 0
 ---> Using cache
 ---> e81a5fa7a8c4
Step 4/8 : RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy \"${http_proxy}\";" >> /etc/apt/apt.conf; fi
 ---> Using cache
 ---> 464a69817f82
Step 5/8 : RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy \"${https_proxy}\";" >> /etc/apt/apt.conf; fi
 ---> Using cache
 ---> 0b228360b5bb
Step 6/8 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 8edd20a56660
Step 7/8 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> f3416dddf487
Step 8/8 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 2a41ff46ab4f
Successfully built 2a41ff46ab4f
Successfully tagged symbolicator-cleanup-self-hosted-local:latest
Building web
Sending build context to Docker daemon  32.26kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 71796743f12f
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 3029cebf4212
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> fe02ba5be9a9
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 15f5dafe46f4
Successfully built 15f5dafe46f4
Successfully tagged sentry-self-hosted-local:latest
Building cron
Sending build context to Docker daemon  32.26kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 71796743f12f
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 3029cebf4212
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> fe02ba5be9a9
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 15f5dafe46f4
Successfully built 15f5dafe46f4
Successfully tagged sentry-self-hosted-local:latest
Building worker
Sending build context to Docker daemon  32.26kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 71796743f12f
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 3029cebf4212
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> fe02ba5be9a9
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 15f5dafe46f4
Successfully built 15f5dafe46f4
Successfully tagged sentry-self-hosted-local:latest
Building ingest-consumer
Sending build context to Docker daemon  32.26kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 71796743f12f
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 3029cebf4212
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> fe02ba5be9a9
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 15f5dafe46f4
Successfully built 15f5dafe46f4
Successfully tagged sentry-self-hosted-local:latest
Building ingest-replay-recordings
Sending build context to Docker daemon  32.26kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 71796743f12f
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 3029cebf4212
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> fe02ba5be9a9
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 15f5dafe46f4
Successfully built 15f5dafe46f4
Successfully tagged sentry-self-hosted-local:latest
Building post-process-forwarder-errors
Sending build context to Docker daemon  32.26kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 71796743f12f
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 3029cebf4212
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> fe02ba5be9a9
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 15f5dafe46f4
Successfully built 15f5dafe46f4
Successfully tagged sentry-self-hosted-local:latest
Building post-process-forwarder-transactions
Sending build context to Docker daemon  32.26kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 71796743f12f
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 3029cebf4212
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> fe02ba5be9a9
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 15f5dafe46f4
Successfully built 15f5dafe46f4
Successfully tagged sentry-self-hosted-local:latest
Building subscription-consumer-events
Sending build context to Docker daemon  32.26kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 71796743f12f
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 3029cebf4212
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> fe02ba5be9a9
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 15f5dafe46f4
Successfully built 15f5dafe46f4
Successfully tagged sentry-self-hosted-local:latest
Building subscription-consumer-transactions
Sending build context to Docker daemon  32.26kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 71796743f12f
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 3029cebf4212
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> fe02ba5be9a9
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 15f5dafe46f4
Successfully built 15f5dafe46f4
Successfully tagged sentry-self-hosted-local:latest
Building sentry-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/8 : ARG BASE_IMAGE
Step 2/8 : FROM ${BASE_IMAGE}
 ---> 15f5dafe46f4
Step 3/8 : USER 0
 ---> Running in bbf4551a1347
Removing intermediate container bbf4551a1347
 ---> ec8af7def1d0
Step 4/8 : RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy \"${http_proxy}\";" >> /etc/apt/apt.conf; fi
 ---> Running in f033a4f1ecfd
Removing intermediate container f033a4f1ecfd
 ---> 8b73e82e9835
Step 5/8 : RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy \"${https_proxy}\";" >> /etc/apt/apt.conf; fi
 ---> Running in 64982fa74d3f
Removing intermediate container 64982fa74d3f
 ---> 3db06756e255
Step 6/8 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Running in 50f376a1f61b
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [236 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
Fetched 8642 kB in 2s (3928 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  sensible-utils
Suggested packages:
  anacron logrotate checksecurity
Recommended packages:
  default-mta | mail-transport-agent
The following NEW packages will be installed:
  cron sensible-utils
0 upgraded, 2 newly installed, 0 to remove and 16 not upgraded.
Need to get 114 kB of archives.
After this operation, 314 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main amd64 sensible-utils all 0.0.14 [14.8 kB]
Get:2 http://deb.debian.org/debian bullseye/main amd64 cron amd64 3.0pl1-137 [99.6 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 114 kB in 0s (696 kB/s)
Selecting previously unselected package sensible-utils.
(Reading database ... 7031 files and directories currently installed.)
Preparing to unpack .../sensible-utils_0.0.14_all.deb ...
Unpacking sensible-utils (0.0.14) ...
Selecting previously unselected package cron.
Preparing to unpack .../cron_3.0pl1-137_amd64.deb ...
Unpacking cron (3.0pl1-137) ...
Setting up sensible-utils (0.0.14) ...
Setting up cron (3.0pl1-137) ...
Adding group `crontab' (GID 101) ...
Done.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Removing intermediate container 50f376a1f61b
 ---> 006f8b9a9c5e
Step 7/8 : COPY entrypoint.sh /entrypoint.sh
 ---> ad9d91ad69ea
Step 8/8 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Running in f3938ddfc178
Removing intermediate container f3938ddfc178
 ---> 2ba766696ef6
Successfully built 2ba766696ef6
Successfully tagged sentry-cleanup-self-hosted-local:latest
relay uses an image, skipping
nginx uses an image, skipping

Docker images built.

▶ Downloading and installing wal2json ...

▶ Bootstrapping and migrating Snuba ...
Creating network "sentry-self-hosted_default" with the default driver
Creating sentry-self-hosted_zookeeper_1 ...
Creating sentry-self-hosted_clickhouse_1 ...
Creating sentry-self-hosted_redis_1      ...
Creating sentry-self-hosted_clickhouse_1 ... done
Creating sentry-self-hosted_zookeeper_1  ... done
Creating sentry-self-hosted_redis_1      ... done
Creating sentry-self-hosted_kafka_1      ...
Creating sentry-self-hosted_kafka_1      ... done
Creating sentry-self-hosted_snuba-api_run ...
Creating sentry-self-hosted_snuba-api_run ... done
2023-03-30 13:02:26,254 Initializing Snuba...
2023-03-30 13:02:29,441 Snuba initialization took 3.188241905067116s
2023-03-30 13:02:29,933 Initializing Snuba...
2023-03-30 13:02:33,088 Snuba initialization took 3.155637540970929s
2023-03-30 13:02:33,090 Attempting to connect to Kafka (attempt 0)...
2023-03-30 13:02:33,123 Connected to Kafka on attempt 0
2023-03-30 13:02:33,124 Creating Kafka topics...
Creating sentry-self-hosted_snuba-api_run ...
Creating sentry-self-hosted_snuba-api_run ... done
2023-03-30 13:02:35,223 Initializing Snuba...
2023-03-30 13:02:38,466 Snuba initialization took 3.244335658964701s
2023-03-30 13:02:38,972 Initializing Snuba...
2023-03-30 13:02:42,177 Snuba initialization took 3.2055365840205923s
Finished running migrations

▶ Creating additional Kafka topics ...

▶ Setting up / migrating database ...
Creating sentry-self-hosted_smtp_1 ...
Creating sentry-self-hosted_symbolicator_1 ...
Creating sentry-self-hosted_postgres_1     ...
Creating sentry-self-hosted_memcached_1    ...
Creating sentry-self-hosted_snuba-outcomes-consumer_1 ...
Creating sentry-self-hosted_snuba-consumer_1          ...
Creating sentry-self-hosted_snuba-replacer_1          ...
Creating sentry-self-hosted_snuba-transactions-consumer_1 ...
Creating sentry-self-hosted_snuba-sessions-consumer_1     ...
Creating sentry-self-hosted_snuba-subscription-consumer-events_1 ...
Creating sentry-self-hosted_snuba-api_1                          ...
Creating sentry-self-hosted_snuba-subscription-consumer-transactions_1 ...
Creating sentry-self-hosted_smtp_1                                     ... done
Creating sentry-self-hosted_postgres_1                                 ... done
Creating sentry-self-hosted_snuba-outcomes-consumer_1                  ... done
Creating sentry-self-hosted_snuba-consumer_1                           ... done
Creating sentry-self-hosted_symbolicator_1                             ... done
Creating sentry-self-hosted_memcached_1                                ... done
Creating sentry-self-hosted_snuba-replacer_1                           ... done
Creating sentry-self-hosted_snuba-sessions-consumer_1                  ... done
Creating sentry-self-hosted_snuba-transactions-consumer_1              ... done
Creating sentry-self-hosted_snuba-subscription-consumer-events_1       ... done
Creating sentry-self-hosted_snuba-subscription-consumer-transactions_1 ... done
Creating sentry-self-hosted_snuba-api_1                                ... done
Creating sentry-self-hosted_web_run                                    ...
Creating sentry-self-hosted_web_run                                    ... done
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
13:03:25 [INFO] sentry.plugins.github: apps-not-configured
Running migrations for default
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, nodestore, replays, sentry, sessions, sites, social_auth
Running migrations:
  Applying sentry.0386_backfill_monitor_env_checkins... OK
  Applying sentry.0387_add_until_escalating_column_to_groupsnooze... OK
  Applying sentry.0388_remove_unique_constraint_artifact_bundle... OK
  Applying sentry.0389_nullify_debug_id_artifact_bundle_field... OK
  Applying sentry.0390_remove_field_in_bundle_model... OK
  Applying sentry.0391_remove_field_in_bundle_model_from_db... OK
  Applying sentry.0392_add_date_uploaded_field_to_bundle... OK
Creating missing DSNs
Correcting Group.num_comments counter

▶ Setting up GeoIP integration ...
Setting up IP address geolocation ...
IP address geolocation database already exists.
IP address geolocation is not configured for updates.
See https://develop.sentry.dev/self-hosted/geolocation/ for instructions.
Error setting up IP address geolocation.


-----------------------------------------------------------------

You're all done! Run the following command to get Sentry running:

  docker-compose up -d

-----------------------------------------------------------------
```

</details>

<details>
<summary>
Docker logs (I can't see anything valuable here)
</summary>

Project ID: 3

```
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
clickhouse_1                                | 2023.03.30 14:40:07.196378 [ 225 ] {} <Information> HTTPHandler: Done processing query
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
ingest-consumer_1                           | 14:40:07 [INFO] sentry.batching-kafka-consumer: Worker flush took 127ms
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:07 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
clickhouse_1                                | 2023.03.30 14:40:08.403171 [ 212 ] {f8cb1900-3c08-4341-aba5-5fcaf271bd94} <Information> executeQuery: Read 15 rows, 873.00 B in 0.006 sec., 2637 rows/sec., 149.90 KiB/sec.
clickhouse_1                                | 2023.03.30 14:40:08.403875 [ 212 ] {} <Information> HTTPHandler: Done processing query
ingest-consumer_1                           | 14:40:08 [INFO] sentry.batching-kafka-consumer: Flushing 22 items (from {('ingest-transactions', 0): [25629780, 25629801]}): forced:False size:False time:True
clickhouse_1                                | 2023.03.30 14:40:08.415848 [ 225 ] {75ab4863-3978-41d4-8939-05225316be8e} <Information> executeQuery: Read 15 rows, 25.68 KiB in 0.017 sec., 884 rows/sec., 1.48 MiB/sec.
clickhouse_1                                | 2023.03.30 14:40:08.417326 [ 225 ] {} <Information> HTTPHandler: Done processing query
ingest-consumer_1                           | 14:40:08 [INFO] sentry.batching-kafka-consumer: Worker flush took 142ms
clickhouse_1                                | 2023.03.30 14:40:09.739679 [ 212 ] {8dd3c277-b2df-43ed-a74b-04a63ce20ba2} <Information> executeQuery: Read 22 rows, 1.24 KiB in 0.008 sec., 2926 rows/sec., 165.22 KiB/sec.
clickhouse_1                                | 2023.03.30 14:40:09.740161 [ 212 ] {} <Information> HTTPHandler: Done processing query
clickhouse_1                                | 2023.03.30 14:40:09.743870 [ 225 ] {e1fd995b-32d4-4005-94ea-80247b7544bf} <Information> executeQuery: Read 22 rows, 37.47 KiB in 0.013 sec., 1731 rows/sec., 2.88 MiB/sec.
clickhouse_1                                | 2023.03.30 14:40:09.744243 [ 225 ] {} <Information> HTTPHandler: Done processing query
nginx_1                                     | 192.168.1.84 - - [30/Mar/2023:14:40:09 +0000] "POST /api/11/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.11.0" "-"
nginx_1                                     | 192.168.1.83 - - [30/Mar/2023:14:40:10 +0000] "POST /api/6/envelope/ HTTP/1.1" 200 41 "-" "sentry.php/3.7.0" "-"
nginx_1                                     | 192.168.90.2 - - [30/Mar/2023:14:40:10 +0000] "POST /api/3/envelope/?sentry_key=********&sentry_client=sentry.javascript.vue%2F7.44.2 HTTP/1.1" 200 41 "https://hands.********.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" "192.168.3.45"
ingest-consumer_1                           | 14:40:11 [INFO] sentry.batching-kafka-consumer: Flushing 2 items (from {('ingest-transactions', 0): [25629802, 25629803]}): forced:False size:False time:True
ingest-consumer_1                           | 14:40:11 [INFO] sentry.batching-kafka-consumer: Worker flush took 12ms

```

</details>

### Event ID

I can't see any errors being reported from my logs, so not sure where to start with this. Any ideas?

I've checked and I don't think it's related to #2002 or #2052, but if there's any basic troubleshooting I've missed let me know.

Also tested it against sentry.io, and it's working ok so assume it's some sort of configuration issue on my side.

**Comment by hubertdeng123** [comment]
Ok, that looks pretty normal to me. Unsure exactly what might be going wrong here. Replay metadata is stored in Clickhouse and Replay segments are stored in Postgres. 

1. Can you check the `replays_local` table in Clickhouse? How many entries do you see there? Is it empty? 
2. What is in the postgres table `replays_replayrecordingsegment`? Is there any data there?

**Comment by ffaen** [comment]
> 1. Can you check the `replays_local` table in Clickhouse? How many entries do you see there? Is it empty?

```bash
SELECT count(*)
FROM replays_local

┌─count()─┐
│       0 │
└─────────┘

1 rows in set. Elapsed: 0.039 sec.
```

> 2. What is in the postgres table `replays_replayrecordingsegment`? Is there any data there?

```bash
postgres=# select count(*) from replays_replayrecordingsegment;
 count
-------
     0
(1 row)
```

This is a sample request I'm sending to the sentry backend - doesn't look like anything untoward...

```
{"event_id":"f9c3c6bf46e9406c93f3f9e56aeb6ed7","sent_at":"2023-03-31T22:59:41.852Z","sdk":{"name":"sentry.javascript.vue","version":"7.44.2"}}
{"type":"replay_event"}
{"type":"replay_event","timestamp":1680303581.851,"error_ids":[],"trace_ids":["65901e46c21f4934bbedffe849eefd44"],"urls":["https://****.********.***/app/","https://****.********.***/app/...","https://****.********.***/app/...","https://****.********.***/app/"],"replay_id":"f9c3c6bf46e9406c93f3f9e56aeb6ed7","segment_id":2,"replay_type":"session","event_id":"f9c3c6bf46e9406c93f3f9e56aeb6ed7","environment":"production","release":"c0175d2352bb3ee553f7183f9cfcbae57e9dfbe4","sdk":{"integrations":["InboundFilters","FunctionToString","TryCatch","Breadcrumbs","GlobalHandlers","LinkedErrors","Dedupe","HttpContext","Replay","BrowserTracing"],"name":"sentry.javascript.vue","version":"7.44.2"},"user":{"id":249,"username":"Ffaen *****"},"sdkProcessingMetadata":{},"request":{"url":"https://****.********.***/app/","headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"}},"platform":"javascript","contexts":{"replay":{"session_sample_rate":1,"error_sample_rate":1}}}
{"type":"replay_recording","length":6586}
{"segment_id":2}
xÈA
{{snip}}
PÔ[ZÚÈ¥ÀJYÆÐÔÔØÔÄjkÿÿµy|

```

Returns 200, and a standard `{"id":"f9c3c6bf46e9406c93f3f9e56aeb6ed7"}` response.

**Comment by hubertdeng123** [comment]
Yeah, that's not normal since the replay data should be in Clickhouse and Postgres. Unsure why this might be the case 🤔

**Comment by ffaen** [comment]
Would you suggest a reinstall? Is it possible to reinstall while keeping data intact?

**Comment by alkanna** [comment]
Facing the exact same issue here

**Comment by zivkovic** [comment]
Same issue here.

**Comment by oakland** [comment]
Same issue. Is there anybody can give me some advice on debugging?

**Comment by hubertdeng123** [comment]
Few questions I have for people for data points:

1. Are you using a clean install or upgrading from an older version of self-hosted?
2. What SDK are you using?

**Comment by fpotter** [comment]
Thanks for investigating, @hubertdeng123!  I'm also not seeing replays on 2023.3.1.

> Are you using a clean install or upgrading from an older version of self-hosted?

Upgraded older install from 2023.2 (if it helps, this install goes back a couple of years.)

> What SDK are you using?

7.37.2

**Comment by oakland** [comment]
> 1. Are you using a clean install or upgrading from an older version of self-hosted?

Upgrading from an older version of self-hosted. 
Before: Sentry 22.11.0.dev07eb2f1d
After: Sentry 23.4.0.dev0

> 2. What SDK are you using?

"@sentry/react": "7.43.0"
"@sentry/tracing": "7.43.0"
"@sentry/webpack-plugin": "1.20.0"

> 3. CPU Architecture?

Architecture:          x86_64

**Comment by loremaps** [comment]
> 1. Are you using a clean install or upgrading from an older version of self-hosted?

Upgrading from an older version of self-hosted.
Before: Sentry 23.2.0
After: Sentry 23.3.1

> 2. What SDK are you using?

"@sentry/node": "^7.45.0"
"@sentry/angular-ivy": "^7.45.0"
"@sentry/types": "7.45.0"

> 3. CPU Architecture?

Architecture: x86_64

**Comment by ffaen** [comment]
> Few questions I have for people for data points:
> 
> 1. Are you using a clean install or upgrading from an older version of self-hosted?

My upgrade path has been: 22.1.0 -> 22.4.0 -> 22.6.0 -> 22.9.0 -> 23.3.0 -> 23.3.1

> 2. What SDK are you using?

@sentry/browser@7.44.2
@sentry/integrations@7.44.2
@sentry/tracing@7.44.2
@sentry/vue@7.44.2


> 3. CPU Architecture?

x86_64

**Comment by Michal-Miko** [comment]
Similar issues here.

> Are you using a clean install or upgrading from an older version of self-hosted?

Upgrade history: 22.8.0 -> 22.10.0 -> 23.3.1

> What SDK are you using?

"@sentry/react": "^7.47.0",
"@sentry/tracing": "^7.47.0",

> CPU Architecture?

x86_64

**Comment by oakland** [comment]
> Seems like these are all happening with upgraded versions of self-hosted, wonder if that's related here

Is it possible to uninstall Sentry, and re-install it to bypass this problem?

**Comment by ktowen** [comment]
Any ideas about this? I'm having the same problem

> Are you using a clean install or upgrading from an older version of self-hosted?

22.7.0 -> 23.3.1

> What SDK are you using?

@sentry/react@7.48.0

> CPU Architecture?

x86_64

> Can you check the replays_local table in Clickhouse? How many entries do you see there? Is it empty?
> What is in the postgres table replays_replayrecordingsegment? Is there any data there?

Both empty

**Comment by ffaen** [comment]
Issue still present in 23.4.0

**Comment by adrianguenter** [comment]
+1 on `23.4.0`, upgraded from `23.2.0`


```
[Request]
{"event_id":"2279a195fc774e4897f122a0ff8eef6b","sent_at":"2023-05-04T23:24:14.213Z","sdk":{"name":"sentry.javascript.browser","version":"7.51.0"}}
{"type":"replay_event"}
...

[Response (200)]
{"id":"2279a195fc774e4897f122a0ff8eef6b"}
```

```
SELECT count(*)
FROM replays_local

┌─count()─┐
│       0 │
└─────────┘

1 rows in set. Elapsed: 0.015 sec.
```

```
psql (14.5 (Debian 14.5-2.pgdg110+2))
Type "help" for help.

postgres=# select count(*) from replays_replayrecordingsegment;
 count 
-------
     0
(1 row)
```

**Comment by Spice-King** [comment]
Might as well chip in details on my end for my install.

> 1. Are you using a clean install or upgrading from an older version of self-hosted?

Upgraded, started back on 21.12.0 (yes, back when this repo was called `onpremise`), assorted 22.x versions, then 23.2.0, 23.3.1, and finally 23.4.0.

> 2. What SDK are you using?

@sentry/vue v7.49.0, v7.51.1, prior versions used, but never had replay enabled client side in those, plus my tunnel happened to choke on requests with replay payloads before I fixed it.

> 3. CPU Architecture?

x86_64

```
ClickHouse client version 20.3.9.70 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.3.9 revision 54433.

75a90aa25085 :) select count(*) from replays_local

SELECT count(*)
FROM replays_local

┌─count()─┐
│       0 │
└─────────┘

1 rows in set. Elapsed: 0.002 sec. 
```

```
postgres=# select count(*) from replays_replayrecordingsegment;
 count 
-------
     0
(1 row)
```

If you want me to poke it and get more details, feel free to mention me and I'll see what I can dig up.

**Comment by goguda** [comment]
Same issue here

**Comment by ffaen** [comment]
Issue still present in 23.5.0.

Current upgrade path: 22.1.0 -> 22.4.0 -> 22.6.0 -> 22.9.0 -> 23.3.0 -> 23.3.1 -> 23.4.0 -> 23.5.0

**Comment by Mordred** [comment]
> Issue still present in 23.5.0.
> 
> Current upgrade path: 22.1.0 -> 22.4.0 -> 22.6.0 -> 22.9.0 -> 23.3.0 -> 23.3.1 -> 23.4.0 -> 23.5.0

I've upgraded to 23.5.0 yesterday and it is working for me. I had custom `docker-compose.override.yml` which I deleted. 
(_Previously I had `KAFKA_MESSAGE_MAX_BYTES=25000000` and custom `command` for `memcached`_).

I diffed `sentry/sentry.conf.py` and `sentry/sentry.conf.example.py` and applied changes.

What I noticed is that when you restart by `docker compose restart` it stops working. But `docker compose down && sleep 10 && docker compose up -d` starts services in correct order and replays are displayed correctly. 🤷

**Comment by ffaen** [comment]
> I diffed `sentry/sentry.conf.py` and `sentry/sentry.conf.example.py` and applied changes.

That's interesting - I admit that I hadn't diffed my config in a while and there's a feature flag `organizations:session-replay` that wasn't in my config. I've added it now... but it still doesn't seem to work for me even with the down, sleep, up job.

Is there any other conf.py values that are required to be in that file, but were recently added so maybe missed from update?

@hubertdeng123 may be some useful information there to assist you with your troubleshooting...

**Comment by oakland** [comment]
> docker compose down && sleep 10 && docker compose up -d

Worked for me as well, thanks!

**Comment by zatu22** [comment]
> I diffed sentry/sentry.conf.py and sentry/sentry.conf.example.py and applied changes.

Seems to work for me too.

**Comment by goguda** [comment]
> > Issue still present in 23.5.0.
> > Current upgrade path: 22.1.0 -> 22.4.0 -> 22.6.0 -> 22.9.0 -> 23.3.0 -> 23.3.1 -> 23.4.0 -> 23.5.0
> 
> I upgraded to 23.5.0 yesterday and it is working for me. I had custom `docker-compose.override.yml` which I deleted. (_Previously I had `KAFKA_MESSAGE_MAX_BYTES=25000000` and custom `command` for `memcached`_).
> 
> I diffed `sentry/sentry.conf.py` and `sentry/sentry.conf.example.py` and applied changes.
> 
> What I noticed is that when you restart by `docker compose restart` it stops working. But `docker compose down && sleep 10 && docker compose up -d` starts services in correct order and replays are displayed correctly. shrug

Interesting, so I diffed my files and there definitely were a few differences. Updated sentry.conf.py, tried restarting, no luck. Did a `docker-compose down`, ran install script again, `docker-compose up -d`. Still no luck. Tried restarting again with `docker-compose down && sleep 10 && docker-compose up -d`, still nothing. I've probably tried restarting all containers 3 or 4 times now with no luck still 😕

**Comment by Michal-Miko** [comment]
> > Issue still present in 23.5.0.
> > Current upgrade path: 22.1.0 -> 22.4.0 -> 22.6.0 -> 22.9.0 -> 23.3.0 -> 23.3.1 -> 23.4.0 -> 23.5.0
> 
> I upgraded to 23.5.0 yesterday and it is working for me. I had custom `docker-compose.override.yml` which I deleted. (_Previously I had `KAFKA_MESSAGE_MAX_BYTES=25000000` and custom `command` for `memcached`_).
> 
> I diffed `sentry/sentry.conf.py` and `sentry/sentry.conf.example.py` and applied changes.
> 
> What I noticed is that when you restart by `docker compose restart` it stops working. But `docker compose down && sleep 10 && docker compose up -d` starts services in correct order and replays are displayed correctly. 🤷

My problems were resolved by upgrading to the latest version and updating the configuration file, I think I was missing the session replay feature flag.

**Comment by ffaen** [comment]
Closing off as I think we're all sorted here.
