### ISSUE TITLE
ERROR:  duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by afaianswq** [getsentry/self-hosted#2171]
### Self-Hosted Version

23.5.1

### CPU Architecture

x86_64

### Docker Version

24.0.2

### Docker Compose Version

2.18.1

### Steps to Reproduce

1. Upgrade Sentry from pre-postgres-14 version (i.e. 23.3.0) to latest version
2. Make sure there is a moderate amount of incoming events, and issues are being created
3. Check postgres container logs

### Expected Result

There should be no errors.

### Actual Result

A lot of errors like this:
```
ERROR:  duplicate key value violates unique constraint "sentry_environmentprojec_project_id_environment_i_91da82f2_uniq"
DETAIL:  Key (project_id, environment_id)=(175, 1) already exists.
STATEMENT:  INSERT INTO "sentry_environmentproject" ("project_id", "environment_id", "is_hidden") VALUES (175, 1, NULL) RETURNING "sentry_environmentproject"."id"

ERROR:  duplicate key value violates unique constraint "sentry_grouprelease_group_id_release_id_envi_044354c8_uniq"
DETAIL:  Key (group_id, release_id, environment)=(5040920, 17693, production) already exists.
STATEMENT:  INSERT INTO "sentry_grouprelease" ("project_id", "group_id", "release_id", "environment", "first_seen", "last_seen") VALUES (38, 5040920, 17693, 'production', '2023-06-01T11:40:07.927899+00:00'::timestamptz, '2023-06-01T11:40:07.927899+00:00'::timestamptz) RETURNING "sentry_grouprelease"."id"
```

**Comment by hubertdeng123** [comment]
Do you have install logs? Did that complete without any errors?

**Comment by hubertdeng123** [comment]
Wondering if your sequence is out of sync. Could you see if that is the case using the steps here?
https://stackoverflow.com/questions/4448340/postgresql-duplicate-key-violates-unique-constraint

**Comment by afaianswq** [comment]
Here's what I see:
```
postgres=# select max(id) from sentry_environmentproject;
  max
--------
 792802
(1 row)

postgres=# SELECT nextval('sentry_environmentproject_id_seq');
 nextval
---------
  799322
(1 row)
```

**Comment by AlexanderRydberg** [comment]
Im also having this issue on two sentry-setups

**Comment by roock** [comment]
Similar issue here. Happens after upgrade from 23.3.1 to 23.4.0 with the upgrade to postgresql.
I did have an error during the installation because of duplicate entries in sentry_releaseprojectenvironment which I had to remove manually to get overcome a duplicate key error during reindex.

installation log
```
Re-indexing database: sentry
ERROR:  could not create unique index "sentry_releaseprojectenvironmen_project_id_d2be2f28c78caf7_uniq"
DETAIL:  Key (project_id, release_id, environment_id)=(11, 5198, 2) is duplicated.
Error in install/upgrade-postgres.sh:38.
'docker exec sentry-self-hosted-postgres-1 psql -qAt -U postgres -d ${db} -c "reindex database ${db};"' exited with status 1
-> install.sh:main:33
--> install/upgrade-postgres.sh:source:38
```

```
2023-06-06 15:53:15.444 UTC [15601] STATEMENT:  INSERT INTO "sentry_environmentproject" ("project_id", "environment_id", "is_hidden") VALUES (15, 2, NULL) RETURNING "sentry_environmentproject"."id"
2023-06-06 15:53:35.614 UTC [15705] ERROR:  duplicate key value violates unique constraint "sentry_organizationonboar_organization_id_47e98e05cae29cf3_uniq"
2023-06-06 15:53:35.614 UTC [15705] DETAIL:  Key (organization_id, task)=(2, 5) already exists.
2023-06-06 15:53:35.614 UTC [15705] STATEMENT:  INSERT INTO "sentry_organizationonboardingtask" ("organization_id", "user_id", "status", "completion_seen", "date_completed", "project_id", "data", "task") VALUES (2, NULL, 1, NULL, '2023-06-06T15:53:35.611610+00:00'::timestamptz, 13, '{}', 5) RETURNING "sentry_organizationonboardingtask"."id"
2023-06-06 15:53:35.622 UTC [15706] ERROR:  duplicate key value violates unique constraint "sentry_organizationonboar_organization_id_47e98e05cae29cf3_uniq"
2023-06-06 15:53:35.622 UTC [15706] DETAIL:  Key (organization_id, task)=(2, 5) already exists.
2023-06-06 15:53:35.622 UTC [15706] STATEMENT:  INSERT INTO "sentry_organizationonboardingtask" ("organization_id", "user_id", "status", "completion_seen", "date_completed", "project_id", "data", "task") VALUES (2, NULL, 1, NULL, '2023-06-06T15:53:35.619722+00:00'::timestamptz, 12, '{}', 5) RETURNING "sentry_organizationonboardingtask"."id"
2023-06-06 15:53:40.217 UTC [15748] ERROR:  duplicate key value violates unique constraint "sentry_environmentproject_project_id_29250c1307d3722b_uniq"
2023-06-06 15:53:40.217 UTC [15748] DETAIL:  Key (project_id, environment_id)=(11, 2) already exists.
2023-06-06 15:53:40.217 UTC [15748] STATEMENT:  INSERT INTO "sentry_environmentproject" ("project_id", "environment_id", "is_hidden") VALUES (11, 2, NULL) RETURNING "sentry_environmentproject"."id"
2023-06-06 15:53:40.225 UTC [15749] ERROR:  duplicate key value violates unique constraint "sentry_environmentproject_project_id_29250c1307d3722b_uniq"
2023-06-06 15:53:40.225 UTC [15749] DETAIL:  Key (project_id, environment_id)=(11, 2) already exists.
2023-06-06 15:53:40.225 UTC [15749] STATEMENT:  INSERT INTO "sentry_environmentproject" ("project_id", "environment_id", "is_hidden") VALUES (11, 2, NULL) RETURNING "sentry_environmentproject"."id"
2023-06-06 15:54:03.426 UTC [15898] ERROR:  duplicate key value violates unique constraint "sentry_environmentproject_project_id_29250c1307d3722b_uniq"
2023-06-06 15:54:03.426 UTC [15898] DETAIL:  Key (project_id, environment_id)=(5, 2) already exists.
2023-06-06 15:54:03.426 UTC [15898] STATEMENT:  INSERT INTO "sentry_environmentproject" ("project_id", "environment_id", "is_hidden") VALUES (5, 2, NULL) RETURNING "sentry_environmentproject"."id"
2023-06-06 15:54:37.333 UTC [16129] ERROR:  duplicate key value violates unique constraint "sentry_environmentproject_project_id_29250c1307d3722b_uniq"
2023-06-06 15:54:37.333 UTC [16129] DETAIL:  Key (project_id, environment_id)=(12, 5) already exists.
2023-06-06 15:54:37.333 UTC [16129] STATEMENT:  INSERT INTO "sentry_environmentproject" ("project_id", "environment_id", "is_hidden") VALUES (12, 5, NULL) RETURNING "sentry_environmentproject"."id"
```

```
sentry=# select max(id) from sentry_environmentproject;
  max
-------
 25791
(1 row)

sentry=# SELECT nextval('sentry_environmentproject_id_seq');
 nextval
---------
   75872
(1 row)
```

**Comment by AlexanderRydberg** [comment]
@roock what were the commands you ran?

**Comment by AlexanderRydberg** [comment]
ouch scary :fearful: We have this "issue" on both test and prod-env. Hopefully there will come a official fix for this, I guess that a lot more users have this error. 

Dont know how this effects Sentry tho

**Comment by afaianswq** [comment]
I'd like to highlight that @roock most probably having a different issue. I didn't have any errors during the upgrade. Everything went smoothly, no errors, no warnings. I didn't run any postgres commands manually or interfered with postgres in any other way.

**Comment by AlexanderRydberg** [comment]
@afaianswq I didnt have any errors dring the upgrade either nor any postgres changes manually

**Comment by roock** [comment]
@afaianswq Yeah, I most likely had a different (and probably unique) issue **during** upgrade. **After the upgrade** is completed, I am seeing the same errors in the database log as you are seeing

@AlexanderRydberg @afaianswq Are you missing transactions and or issues inside Sentry when the database errors are happening or is it "just" errors in the database log?

**Comment by AlexanderRydberg** [comment]
As far as I know theres "onlu" erors in the log

**Comment by afaianswq** [comment]
This is a serious issue and it hasn't been fixed. Please reopen and set appropriate status so it won't automatically close again.

**Comment by hubertdeng123** [comment]
> This is a serious issue and it hasn't been fixed. Please reopen and set appropriate status so it won't automatically close again.

Unfortunately there's not much we can do on our side to fix this.

**Comment by hubertdeng123** [comment]
Otherwise, if your self-hosted Sentry instance appears to be working as intended, this shouldn't be something to worry about.

**Comment by hubertdeng123** [comment]
Did you do a backup/restore on the same version of self-hosted? It would be helpful to know the exact versions that you were upgrading to/from. There may have been a failed database migration

**Comment by hubertdeng123** [comment]
Ah yes, some people have reported that 23.7.0 have created issues due to the way some migrations were squashed and the django 3 upgrade in Sentry. We've added documentation to tell users to upgrade to 23.6.2 before moving to versions higher:
https://develop.sentry.dev/self-hosted/releases/

**Comment by branov** [comment]
We have the same issue. Unable to update from 23.3.1 to 23.4.0 or even 23.5.0. 

```
ERROR:  could not create unique index "sentry_environmentproject_project_id_29250c1307d3722b_uniq"
DETAIL:  Key (project_id, environment_id)=(55, 11) is duplicated.
Error in install/upgrade-postgres.sh:38.
```

**Comment by hubertdeng123** [comment]
> We have the same issue. Unable to update from 23.3.1 to 23.4.0 or even 23.5.0.

Did you attempt to upgrade to 23.7.0+ first? Might be why this issue is appearing for you

**Comment by branov** [comment]
Regarding https://develop.sentry.dev/self-hosted/releases/#hard-stops I should upgrade first to 23.6.2 if I'm upgrading prior this version. I did try to upgrade to 23.6.2 but with no luck, same error about the duplicated key.

**Comment by hubertdeng123** [comment]
> Regarding https://develop.sentry.dev/self-hosted/releases/#hard-stops I should upgrade first to 23.6.2 if I'm upgrading prior this version. I did try to upgrade to 23.6.2 but with no luck, same error about the duplicated key.

There may now have been corrupted data in your db, sorry that you're experiencing that. You may need to attempt a clean install to fix your setup.

**Comment by branov** [comment]
> There may now have been corrupted data in your db

No, there are not, I did snapshot restore so my Sentry is still working correctly on 23.3.1.

Well, you closed this bug as "the general fix has been deployed" but I'm not still clear how to hell should I upgrade my Sentry to a newer version.

**Comment by hubertdeng123** [comment]
23.3.1 -> 23.4.0+ would involve the postgres 14 upgrade. See these comments above for reference, they were also experiencing duplicate key errors during the upgrade. They mentioned data was corrupted after having issues with the server. 

https://github.com/getsentry/self-hosted/issues/2171#issuecomment-1579988928
https://github.com/getsentry/self-hosted/issues/2171#issuecomment-1579076488

**Comment by afaianswq** [comment]
> 23.3.1 -> 23.4.0+ would involve the postgres 14 upgrade. See these comments above for reference, they were also experiencing duplicate key errors during the upgrade. They mentioned data was corrupted after having issues with the server.
> 
> [#2171 (comment)](https://github.com/getsentry/self-hosted/issues/2171#issuecomment-1579988928) [#2171 (comment)](https://github.com/getsentry/self-hosted/issues/2171#issuecomment-1579076488)

As I stated in this bug report, these errors are not a result of any DB corruption and that they are occurring AFTER the upgrade, during normal operation.

I am still on version 23.5.2 and there was at least one such error in past hour. If this issue was properly fixed in some later version, please let me know the version number.

**Comment by jsbrain** [comment]
Experiencing the same problem while following the https://develop.sentry.dev/self-hosted/releases/#hard-stops upgrade schema. Now on the latest version and this issue occurred anyways ...

**Comment by afaianswq** [comment]
@hubertdeng123, can you please reopen this issue because it wasn't really fixed?
