### ISSUE TITLE
sentry_environmentproject INSERT errors

### ISSUE THREAD

**Issue by ngatti-tmm** [getsentry/self-hosted#2677]
### Self-Hosted Version

23.1.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

24.0.6

### Steps to Reproduce

Migrated from an old Sentry v7 docker version

### Expected Result

No SQL INSERT errors

### Actual Result

I migrated a Sentry instance several months ago, from an old Sentry v7 self hosted dockerized version to v10, then some v22 relase and then to v23.1.1. So, many migrations have been done.
It seems to be working mostly ok but I was debugging an issue with "missing organization" error and noticed some errors on the postgres logs:

`ERROR:  duplicate key value violates unique constraint "sentry_environmentproject_project_id_29250c1307d3722b_uniq"
DETAIL:  Key (project_id, environment_id)=(34, 4) already exists.
STATEMENT:  INSERT INTO "sentry_environmentproject" ("project_id", "environment_id", "is_hidden") VALUES (34, 4, NULL) RETURNING "sentry_environmentproject"."id"
ERROR:  duplicate key value violates unique constraint "sentry_environmentproject_project_id_29250c1307d3722b_uniq"
DETAIL:  Key (project_id, environment_id)=(47, 4) already exists.
STATEMENT:  INSERT INTO "sentry_environmentproject" ("project_id", "environment_id", "is_hidden") VALUES (47, 4, NULL) RETURNING "sentry_environmentproject"."id"
ERROR:  duplicate key value violates unique constraint "sentry_environmentproject_project_id_29250c1307d3722b_uniq"
DETAIL:  Key (project_id, environment_id)=(17, 4) already exists.
STATEMENT:  INSERT INTO "sentry_environmentproject" ("project_id", "environment_id", "is_hidden") VALUES (17, 4, NULL) RETURNING "sentry_environmentproject"."id"
ERROR:  duplicate key value violates unique constraint "sentry_grouprelease_group_id_46ba6e430d088d04_uniq"
DETAIL:  Key (group_id, release_id, environment)=(23964, 2, prod) already exists.
STATEMENT:  INSERT INTO "sentry_grouprelease" ("project_id", "group_id", "release_id", "environment", "first_seen", "last_seen") VALUES (34, 23964, 2, 'prod', '2023-12-26T17:48:05.106860+00:00'::timestamptz, '2023-12-26T17:48:05.106860+00:00'::timestamptz) RETURNING "sentry_grouprelease"."id"
ERROR:  duplicate key value violates unique constraint "sentry_grouprelease_group_id_46ba6e430d088d04_uniq"
DETAIL:  Key (group_id, release_id, environment)=(23964, 2, prod) already exists.
STATEMENT:  INSERT INTO "sentry_grouprelease" ("project_id", "group_id", "release_id", "environment", "first_seen", "last_seen") VALUES (34, 23964, 2, 'prod', '2023-12-26T17:48:05.022607+00:00'::timestamptz, '2023-12-26T17:48:05.022607+00:00'::timestamptz) RETURNING "sentry_grouprelease"."id"
ERROR:  duplicate key value violates unique constraint "sentry_grouprelease_group_id_46ba6e430d088d04_uniq"
DETAIL:  Key (group_id, release_id, environment)=(23964, 2, prod) already exists.
STATEMENT:  INSERT INTO "sentry_grouprelease" ("project_id", "group_id", "release_id", "environment", "first_seen", "last_seen") VALUES (34, 23964, 2, 'prod', '2023-12-26T17:48:05.129340+00:00'::timestamptz, '2023-12-26T17:48:05.129340+00:00'::timestamptz) RETURNING "sentry_grouprelease"."id"`

This is my sentry_environmentproject description:

```
sentry_postgres=# \d sentry_environmentproject;
                             Table "public.sentry_environmentproject"
     Column     |  Type   |                               Modifiers
----------------+---------+------------------------------------------------------------------------
 id             | bigint  | not null default nextval('sentry_environmentproject_id_seq'::regclass)
 project_id     | bigint  | not null
 environment_id | bigint  | not null
 is_hidden      | boolean |
Indexes:
    "sentry_environmentproject_pkey" PRIMARY KEY, btree (id)
    "sentry_environmentproject_project_id_29250c1307d3722b_uniq" UNIQUE CONSTRAINT, btree (project_id, environment_id)
    "sentry_environmentproject_environment_id" btree (environment_id)
    "sentry_environmentproject_project_id" btree (project_id)
Foreign-key constraints:
    "environment_id_refs_id_ab2491b4" FOREIGN KEY (environment_id) REFERENCES sentry_environment(id) DEFERRABLE INITIALLY DEFERRED
    "project_id_refs_id_cf2e01df" FOREIGN KEY (project_id) REFERENCES sentry_project(id) DEFERRABLE INITIALLY DEFERRED

```

and this is sentry_grouprelease
```
sentry_postgres=# \d sentry_grouprelease;
                                    Table "public.sentry_grouprelease"
   Column    |           Type           |                            Modifiers
-------------+--------------------------+------------------------------------------------------------------
 id          | bigint                   | not null default nextval('sentry_grouprelease_id_seq'::regclass)
 project_id  | bigint                   | not null
 group_id    | bigint                   | not null
 release_id  | integer                  | not null
 environment | character varying(64)    | not null
 first_seen  | timestamp with time zone | not null
 last_seen   | timestamp with time zone | not null
Indexes:
    "sentry_grouprelease_pkey" PRIMARY KEY, btree (id)
    "sentry_grouprelease_group_id_46ba6e430d088d04_uniq" UNIQUE CONSTRAINT, btree (group_id, release_id, environment)
    "sentry_grouprelease_group_id_first_seen_53fc35ds" btree (group_id, first_seen)
    "sentry_grouprelease_group_id_last_seen_g8v2sk7c" btree (group_id, last_seen DESC)
    "sentry_grouprelease_last_seen" btree (last_seen)
    "sentry_grouprelease_project_id" btree (project_id)
    "sentry_grouprelease_release_id" btree (release_id)
Check constraints:
    "sentry_grouprelease_release_id_check" CHECK (release_id >= 0)
```

Can someone tell me if tables schemas are correct? or where can I find a DB schema for 23.1.1. version? 

Thanks.

**Comment by azaslavsky** [comment]
Those constraints that you're tripping over (project_id + environment for the first case, group_id + environment + release_id for the second) seem correct, and were in place by 23.1.1. Can you deduce which other docker container was making these failing calls? I suspect that some job tried to write data twice, either due to the migration or due to a bug that has since been fixed in later releases.

**Comment by ngatti-tmm** [comment]
I've migrated to 23.12.1, I still see the errors, although I can't see any bug or misbehaviour on the services.
I am not sure which other container is triggering the error. I can't correlate the error with other logs.
Here is a portion of logs when the error happens, including all containers, a few seconds after and before the postgres error:

```
nginx-1    | 172.18.0.11 - - [28/Dec/2023:15:37:00 +0000] "POST /api/16/envelope/ HTTP/1.1" 200 41 "-" "sentry.php.symfony/4.12.0" "172.71.99.13"
web-1      | 15:37:03 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.project_configs.RelayProjectConfigsEndpoint' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/projectconfigs/' caller_ip='172.18.0.52' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.012911319732666016 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
nginx-1    | 172.18.0.11 - - [28/Dec/2023:15:37:04 +0000] "POST /api/34/envelope/ HTTP/1.1" 200 41 "-" "sentry.php.symfony/4.7.0" "172.71.103.99"
nginx-1    | 172.18.0.11 - - [28/Dec/2023:15:37:06 +0000] "POST /api/45/envelope/ HTTP/1.1" 200 41 "-" "sentry.php.symfony/4.10.0" "172.71.182.138"
web-1      | 15:37:06 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.project_configs.RelayProjectConfigsEndpoint' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/projectconfigs/' caller_ip='172.18.0.52' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.03750133514404297 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
web-1      | 15:37:06 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.project_configs.RelayProjectConfigsEndpoint' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/projectconfigs/' caller_ip='172.18.0.52' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.014922142028808594 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
postgres-1 | 2023-12-28 15:37:06.963 UTC [96654] ERROR:  duplicate key value violates unique constraint "sentry_environmentproject_project_id_29250c1307d3722b_uniq"
postgres-1 | 2023-12-28 15:37:06.963 UTC [96654] DETAIL:  Key (project_id, environment_id)=(45, 4) already exists.
postgres-1 | 2023-12-28 15:37:06.963 UTC [96654] STATEMENT:  INSERT INTO "sentry_environmentproject" ("project_id", "environment_id", "is_hidden") VALUES (45, 4, NULL) RETURNING "sentry_environmentproject"."id"
nginx-1    | 172.18.0.11 - - [28/Dec/2023:15:37:11 +0000] "POST /api/34/envelope/ HTTP/1.1" 200 41 "-" "sentry.php.symfony/4.7.0" "172.71.103.217"
nginx-1    | 172.18.0.11 - - [28/Dec/2023:15:37:13 +0000] "POST /api/34/envelope/ HTTP/1.1" 200 41 "-" "sentry.php.symfony/4.7.0" "172.71.103.21"
web-1      | 15:37:13 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.project_configs.RelayProjectConfigsEndpoint' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/projectconfigs/' caller_ip='172.18.0.52' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.01391291618347168 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
nginx-1    | 172.18.0.11 - - [28/Dec/2023:15:37:15 +0000] "POST /api/17/envelope/ HTTP/1.1" 200 41 "-" "sentry.php.symfony/4.3.0" "172.71.94.210"
web-1      | 15:37:23 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.project_configs.RelayProjectConfigsEndpoint' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/projectconfigs/' caller_ip='172.18.0.52' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.012635231018066406 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')

```

I even removed one of those entries manually from the database (previous backup):

```
sentry_postgres=# SELECT * FROM sentry_environmentproject WHERE project_id=45 AND environment_id=4;
   id   | project_id | environment_id | is_hidden
--------+------------+----------------+-----------
 172739 |         45 |              4 |
sentry_postgres=# DELETE FROM sentry_environmentproject WHERE project_id=45 AND environment_id=4;

```
 And they are created again and then the error starts to happen again.

Thanks

**Comment by hubertdeng123** [comment]
Is your sentry instance operational? The `duplicate key value violates unique constraint` error is a result of an implementation detail during our usage in older versions of Postgres that didn't support UPSERT. If your sentry instance is working properly, this is not something I'd worry about.

See here: https://github.com/getsentry/sentry/issues/8004

**Comment by ngatti-tmm** [comment]
Yes, it is working correctly, I haven't seen any other errors nor strange GUI behaviours. Ok, I will ignore those errors. Thanks for the info.
